export const data = {
  products: [
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: './images/mobile-page-1.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '2',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-2.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '3',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-3.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '4',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-4.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '5',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-5.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '6',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-6.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '7',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-7.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '8',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-8.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '9',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-9.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '10',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-10.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '11',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-11.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '12',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-12.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '13',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-13.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '14',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-14.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '15',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-15.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '16',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-16.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '17',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-17.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '18',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-18.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '19',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-19.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '20',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-20.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-21.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-22.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-23.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-24.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-25.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-26.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-27.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-28.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-29.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-30.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-31.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-32.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-33.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-33.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-35.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '1',
      name: 'samsung Galaxy A04',
      image: '/images/mobile-page-36.webp',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
  ],
}
export const watches = {
  watchSub: [
    {
      id: '1',
      image: '/images/watch-header-1.jpg',
      name: 'mibro watches',
      url: '/smart-watches/mibro',
    },
    {
      id: '2',
      image: '/images/watch-header-2.jpg',
      name: 'kieslect watch',
      url: '/smart-watches/kieslect',
    },
    {
      id: '3',
      image: '/images/watch-header-3.jpg',
      name: 'zero watches',
      url: '/smart-watches/zero',
    },
    {
      id: '4',
      image: '/images/watch-header-4.jpg',
      name: 'assorted watches',
      url: '/smart-watches/assorted',
    },
    {
      id: '5',
      image: '/images/watch-header-5.jpg',
      name: 'dany watches',
      url: '/smart-watches/dany',
    },
    {
      id: '6',
      image: '/images/watch-header-6.jpg',
      name: 'samsung watches',
      url: '/smart-watches/samsung',
    },
    {
      id: '7',
      image: '/images/watch-header-7.jpg',
      name: 'yolo watches',
      url: '/smart-watches/zero',
    },
  ],
  watch: [
    {
      id: '1',
      image: '/images/watch-list-1.webp',
      img: [
        '/images/watch-list-2.webp',
        '/images/watch-list-3.webp',
        '/images/watch-list-4.webp',
        '/images/watch-list-5.webp',
      ],
      color: ['/images/samsung-watches-4-color-gray.webp'],
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '2',
      image: '/images/watch-list-2.webp',
      name: 'samsung Galaxy A04',
      img: [
        '/images/watch-list-2.webp',
        '/images/watch-list-3.webp',
        '/images/watch-list-4.webp',
        '/images/watch-list-5.webp',
      ],
      color: ['/images/samsung-watches-4-color-gray.webp'],
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '3',
      image: '/images/watch-list-3.webp',
      img: [
        '/images/watch-list-2.webp',
        '/images/watch-list-3.webp',
        '/images/watch-list-4.webp',
        '/images/watch-list-5.webp',
      ],
      color: ['/images/samsung-watches-4-color-gray.webp'],
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '4',
      image: '/images/watch-list-4.webp',
      img: [
        '/images/watch-list-2.webp',
        '/images/watch-list-3.webp',
        '/images/watch-list-4.webp',
        '/images/watch-list-5.webp',
      ],
      color: ['/images/samsung-watches-4-color-gray.webp'],
      name: 'Samsung Galaxy Watch 4 Classic Bluetooth 46mm (R890)',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '5',
      image: '/images/watch-list-5.webp',
      img: [
        '/images/watch-list-2.webp',
        '/images/watch-list-3.webp',
        '/images/watch-list-4.webp',
        '/images/watch-list-5.webp',
      ],
      name: 'samsung Galaxy A05',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '6',
      image: '/images/watch-list-6.webp',
      name: 'samsung Galaxy A06',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '7',
      image: '/images/watch-list-7.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '8',
      image: '/images/watch-list-8.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '9',
      image: '/images/watch-list-9.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '10',
      image: '/images/watch-list-10.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '11',
      image: '/images/watch-list-12.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '13',
      image: '/images/watch-list-13.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '14',
      image: '/images/watch-list-14.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '15',
      image: '/images/watch-list-15.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '16',
      image: '/images/watch-list-16.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '17',
      image: '/images/watch-list-17.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '18',
      image: '/images/watch-list-18.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '19',
      image: '/images/watch-list-19.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '20',
      image: '/images/watch-list-20.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '21',
      image: '/images/watch-list-21.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '22',
      image: '/images/watch-list-22.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '23',
      image: '/images/watch-list-23.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '24',
      image: '/images/watch-list-24.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '25',
      image: '/images/watch-list-25.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '26',
      image: '/images/watch-list-26.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '27',
      image: '/images/watch-list-27.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '28',
      image: '/images/watch-list-28.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '29',
      image: '/images/watch-list-29.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '30',
      image: '/images/watch-list-30.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'dany',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '31',
      image: '/images/watch-list-31.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '32',
      image: '/images/watch-list-32.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '33',
      image: '/images/watch-list-33.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '34',
      image: '/images/watch-list-34.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
    {
      id: '35',
      image: '/images/watch-list-35.webp',
      name: 'samsung Galaxy A04',
      price: 23999,
      cut: 24,
      rating: 4.5,
      numReviews: 10,
      brand: 'samsung',
      countInStock: 20,
      description: 'samsung Original Phone',
    },
  ],
}
export const Wireless = {
  wireless: [
    {
      id: '1',
      image: 'images/wireless-1.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '2',
      image: 'images/wireless-2.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '3',
      image: 'images/wireless-3.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '4',
      image: 'images/wireless-4.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '5',
      image: 'images/wireless-5.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '6',
      image: 'images/wireless-6.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '7',
      image: 'images/wireless-7.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '8',
      image: 'images/wireless-8.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '9',
      image: 'images/wireless-9.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '10',
      image: 'images/wireless-10.webp',
      title: 'itel Wireless Earbuds (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
  ],
}
export const SmartWatch = {
  watch: [
    {
      id: '1',
      image: 'images/smart-1.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '2',
      image: 'images/smart-2.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '3',
      image: 'images/smart-3.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '4',
      image: 'images/smart-4.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '5',
      image: 'images/smart-5.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '6',
      image: 'images/smart-6.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '7',
      image: 'images/smart-7.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '8',
      image: 'images/smart-8.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '9',
      image: 'images/smart-9.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
    {
      id: '10',
      image: 'images/smart-10.webp',
      title: 'Smart Watch (KT-01)',
      price: 2499,
      cut: 5000,
      off: '(50% OFF)',
    },
  ],
}
